<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <RootNamespace>SW.Serverless.Samples.RabbitMq.Consumer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SW.Serverless.Samples.RabbitMq\SW.Serverless.Samples.RabbitMq.csproj" />
  </ItemGroup>
</Project>
