<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SW.Serverless.Samples.Greedy</AssemblyName>
    <RootNamespace>SW.Serverless.Samples.Greedy</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SW.Serverless.Sdk/SW.Serverless.Sdk.csproj" />
  </ItemGroup>
</Project>
